---

- hosts: all
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || ( apt update && apt install python -y )
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  roles:
    - role: docker
    - role: ensure-requirements
    - role: install-kubeadm-kubelet-kubectl
    - role: weave
  serial: 1
